name: ğŸ± Run code format and lint
run-name: ğŸ± ${{ github.actor }} is action with format and linter
on:
  push:
    paths-ignore:
      - "public/**"
      - README.md
    branches:
      - master
      - develop
  pull_request:
    paths-ignore:
      - "public/**"
      - README.md
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  Format-Lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - name: Code syntax linting
        run: npm run lint
      - name: Code formatter checking
        run: npx prettier --check .
